"""
Unified checkpoint loader for TRM models.

Handles:
  - Loading architecture config from manifest.yaml or direct specification
  - Instantiating the correct TRM architecture (TRM-MLP or TRM-Att)
  - Loading weights with torch.compile prefix stripping
  - Returning the model in eval mode ready for PTRM inference

Usage:
    from inference.checkpoint_loader import load_model, load_model_from_manifest

    # From a manifest.yaml (generated by download_models.py)
    model, meta = load_model_from_manifest("models/sudoku/manifest.yaml", device="cuda")

    # From explicit parameters
    model, meta = load_model(
        checkpoint_path="models/sudoku/model_mlp.pt",
        arch_config={...},
        dataset_meta={...},
        device="cuda",
    )
"""

import os
import sys
from typing import Any

import torch
import yaml


def _add_trm_to_path():
    """Add TinyRecursiveModels submodule to sys.path so we can import its modules."""
    trm_root = os.path.join(os.path.dirname(__file__), "..", "TinyRecursiveModels")
    trm_root = os.path.abspath(trm_root)
    if trm_root not in sys.path:
        sys.path.insert(0, trm_root)


def _build_model_config(arch_config: dict, dataset_meta: dict, batch_size: int = 1) -> dict:
    """
    Merge architecture config with dataset metadata to produce the full
    config dict expected by TinyRecursiveReasoningModel_ACTV1.

    Args:
        arch_config: Architecture-level hyperparameters (from manifest or YAML).
        dataset_meta: Dataset-level metadata (vocab_size, seq_len, etc.).
        batch_size: Batch size for the model (used for puzzle_emb allocation).

    Returns:
        Complete config dict for model instantiation.
    """
    # Start with arch config, excluding 'loss' and 'name' which are handled separately
    model_cfg = {k: v for k, v in arch_config.items() if k not in ("loss", "name")}

    # Add dataset metadata
    model_cfg.update({
        "batch_size": batch_size,
        "vocab_size": dataset_meta["vocab_size"],
        "seq_len": dataset_meta["seq_len"],
        "num_puzzle_identifiers": dataset_meta.get("num_puzzle_identifiers", 1),
    })

    return model_cfg


def _strip_compile_prefix(state_dict: dict) -> dict:
    """
    Strip torch.compile prefix '_orig_mod.' from state dict keys.
    Also strips the loss head prefix 'model.' to get bare model weights.

    The TRM training pipeline wraps the model in ACTLossHead and then
    torch.compile, producing keys like:
        _orig_mod.model.inner.embed_tokens.weight
    We need:
        inner.embed_tokens.weight
    """
    cleaned = {}
    for key, value in state_dict.items():
        new_key = key

        # Strip torch.compile prefix
        if new_key.startswith("_orig_mod."):
            new_key = new_key[len("_orig_mod."):]

        # Strip ACTLossHead wrapper prefix
        if new_key.startswith("model."):
            new_key = new_key[len("model."):]

        cleaned[new_key] = value

    return cleaned


def _detect_num_puzzle_identifiers(state_dict: dict, arch_config: dict) -> int:
    """
    Detect the actual number of puzzle identifiers from the checkpoint weights.

    The puzzle_emb weights have shape (num_puzzle_identifiers, puzzle_emb_ndim).
    This can differ from the default value in the config when the model was
    trained with per-puzzle embeddings (e.g., ARC with many puzzle types).
    """
    # Look for the puzzle_emb weights key (after prefix stripping)
    puzzle_emb_key = "inner.puzzle_emb.weights"
    if puzzle_emb_key in state_dict:
        return state_dict[puzzle_emb_key].shape[0]

    return arch_config.get("num_puzzle_identifiers", 1)


def load_model(
    checkpoint_path: str,
    arch_config: dict,
    dataset_meta: dict,
    device: str = "cpu",
    batch_size: int = 1,
) -> tuple[torch.nn.Module, dict]:
    """
    Load a TRM model from a checkpoint file with explicit config.

    Args:
        checkpoint_path: Path to the .pt checkpoint file.
        arch_config: Architecture config dict (from manifest or manual).
        dataset_meta: Dataset metadata dict.
        device: Target device ('cpu', 'cuda', 'mps').
        batch_size: Batch size for model instantiation.

    Returns:
        Tuple of (model, metadata_dict) where model is in eval mode on device,
        and metadata_dict contains the arch_config and dataset_meta used.
    """
    _add_trm_to_path()

    # Import TRM model class
    from utils.functions import load_model_class

    # Load and clean state dict
    print(f"Loading checkpoint: {checkpoint_path}")
    raw_state_dict = torch.load(checkpoint_path, map_location="cpu", weights_only=False)
    state_dict = _strip_compile_prefix(raw_state_dict)

    # Detect actual puzzle identifier count from weights
    actual_num_ids = _detect_num_puzzle_identifiers(state_dict, dataset_meta)
    dataset_meta_resolved = dict(dataset_meta)
    dataset_meta_resolved["num_puzzle_identifiers"] = actual_num_ids

    # Build full model config
    model_cfg = _build_model_config(arch_config, dataset_meta_resolved, batch_size)

    # Instantiate the model
    model_class_name = arch_config["name"]
    model_cls = load_model_class(model_class_name)

    with torch.device("cpu"):
        model = model_cls(model_cfg)

    # Load weights
    missing, unexpected = model.load_state_dict(state_dict, strict=False)
    if missing:
        print(f"  Warning: Missing keys ({len(missing)}): {missing[:5]}{'...' if len(missing) > 5 else ''}")
    if unexpected:
        print(f"  Warning: Unexpected keys ({len(unexpected)}): {unexpected[:5]}{'...' if len(unexpected) > 5 else ''}")

    # Move to device and set eval mode
    model = model.to(device)
    model.eval()

    # Count parameters
    num_params = sum(p.numel() for p in model.parameters())
    print(f"  Model loaded: {num_params:,} parameters on {device}")

    metadata = {
        "arch_config": arch_config,
        "dataset_meta": dataset_meta_resolved,
        "checkpoint_path": checkpoint_path,
        "num_params": num_params,
    }

    return model, metadata


def load_model_from_manifest(
    manifest_path: str,
    device: str = "cpu",
    batch_size: int = 1,
    checkpoint_override: str | None = None,
) -> tuple[torch.nn.Module, dict]:
    """
    Load a TRM model using a manifest.yaml generated by download_models.py.

    Args:
        manifest_path: Path to manifest.yaml.
        device: Target device.
        batch_size: Batch size for model instantiation.
        checkpoint_override: Override the default checkpoint filename.

    Returns:
        Tuple of (model, metadata_dict).
    """
    with open(manifest_path, "r") as f:
        manifest = yaml.safe_load(f)

    model_dir = os.path.dirname(manifest_path)
    checkpoint_name = checkpoint_override or manifest["default_checkpoint"]
    checkpoint_path = os.path.join(model_dir, checkpoint_name)

    if not os.path.exists(checkpoint_path):
        raise FileNotFoundError(
            f"Checkpoint not found: {checkpoint_path}. "
            f"Run 'python scripts/download_models.py' first."
        )

    return load_model(
        checkpoint_path=checkpoint_path,
        arch_config=manifest["arch_config"],
        dataset_meta=manifest["dataset_meta"],
        device=device,
        batch_size=batch_size,
    )


def list_available_models(models_dir: str = "models") -> list[dict]:
    """
    List all available downloaded models by scanning for manifest.yaml files.

    Args:
        models_dir: Root directory containing model subdirectories.

    Returns:
        List of dicts with benchmark name, path, and architecture info.
    """
    available = []
    if not os.path.isdir(models_dir):
        return available

    for entry in sorted(os.listdir(models_dir)):
        manifest_path = os.path.join(models_dir, entry, "manifest.yaml")
        if os.path.isfile(manifest_path):
            with open(manifest_path, "r") as f:
                manifest = yaml.safe_load(f)
            arch_type = "TRM-MLP" if manifest["arch_config"].get("mlp_t", False) else "TRM-Att"
            available.append({
                "benchmark": manifest["benchmark"],
                "path": os.path.join(models_dir, entry),
                "manifest_path": manifest_path,
                "arch_type": arch_type,
                "hf_repo": manifest["hf_repo"],
            })

    return available
